### ISSUE TITLE
'flat' name better than 'deshape'??

### ISSUE THREAD

**Issue by goyalyashpal** [uiua-lang/uiua#109]
it's written: "It looks like `♭` because it *flat*tens the array.", how about actually naming it that way? 

As i think "flattening" is a fairly common concept which comes in other prog langs, and also in digital tasks involving layers (image editing etc).

https://www.uiua.org/docs/deshape

https://github.com/uiua-lang/uiua/blob/56c151fb6058b4669adf8a55eb3151988194d35d/src/primitive/defs.rs#L512-L515

**Comment by thekifake** [comment]
I'm for keeping it as "deshape" in the name of consistency; only needing to type "desh" or "resh" for deshape/reshape is easy to get used to because it's just a one letter difference on two functions that I'd venture to guess are pretty commonly used. Making some sort of alias for it where typing `flat` still turns it into `♭` might be worth implementing if there's not a common consensus on this (if you really want to go all out, reshape could be represented as a sharp `♯`; the resemblance between the symbol and what the function does is *there*, I suppose).
