### ISSUE TITLE
[BUG?] Under Deshape

### ISSUE THREAD

**Issue by codereport** [uiua-lang/uiua#4]
Hey @kaikalii, 

I have been adding Uiua to my [array-language-comparisons](https://github.com/codereport/array-language-comparisons) repo and I think I found a bug. This code:

```
Mat ← ↯3_4⇡12

⍜⇌♭ Mat
```
yields 
```
[3 2 1 0 7 6 5 4 11 10 9 8]
```
when I would expect it to yield:
```
╭─           
╷ 11 10 9 8  
   7  6 5 4  
   3  2 1 0  
            ╯
```
similar to the way under deshape works in BQN. Maybe I am doing something wrong though or the behaviour is intended.

Uiua Pad Link: https://uiua.org/pad?src=Mat%20%E2%86%90%20%E2%86%AF3_4%E2%87%A112%0A%0A%E2%8D%9C%E2%87%8C%E2%99%AD%20Mat

---- 

On an unrelated note, I've been playing with Uiua all day since the ArrayCast recording and it is awesome. It is probably my second favorite language now after BQN. I love the `.` and `:` combinators for C and W. Tacit programming feels amazing in Uiua.

**Comment by kaikalii** [comment]
😁 I'm glad you're enjoying it.

That code seems to be working as intended.
`⍜⇌♭ Mat` is equivalent to `⇌♭⇌ Mat`, since `⇌` is trivially invertible.
I haven't actually implemented `⍜♭`, I didn't even think to. I'll put it on my todo.
Currently, the code you are looking for to accomplish that result is `↯∶⇌♭∶△.Mat`.

**Comment by kaikalii** [comment]
Okay, I added it: af40be4
`⍜♭⇌ Mat` should now work how you expect.
