### ISSUE TITLE
Comma instead of underscore

### ISSUE THREAD

**Issue by trans** [uiua-lang/uiua#58]
Have you considered using a comma instead of an underscore for the tacit vector notation?

Writing `1,2,3,4` strikes me as much more intuitive than `1_2_3_4`. 

Of course that would require `over` getting a new symbol, but that doesn’t seem a bad trade off.

**Comment by kaikalii** [comment]
I prefer `_` because it matches the boxy shape of arrays and also conveys a stronger sense of grouping.
Compare these:
```
[1_2_3 4_5_6]
[1,2,3 4,5,6]
```
The first one has straight lines on 3 sides!

This sense of grouping is also important when using it in an argument:
```
↯3_4⇡12
↯3,4⇡12
```
I think the second one kind of looks like the comma is separating the terms, which it is not.
